### ISSUE TITLE
ValueError: y has more than n_class unique elements.

### ISSUE THREAD

**Issue by mmagithub** [ATOMScience-org/AMPL#173]
Hi,
I am trying to run AMPL on a sample dataset for classification. The NN classification model keeps giving me this weird "ValueError: y has more than n_class unique elements." even though the RF & XGBOOST classification models finish without issues.

Any clue for the possible reasons for this error?

Changing deepchem versions did not help.

Thanks,
Marawan

**Comment by stewarthe6** [comment]
Hi Marawan,

Does your dataset have more than two classes? We've been talking about adding more classes, but AMPL currently only supports binary classification.

Stewart

**Comment by mmagithub** [comment]
I see, yes, my dataset has more than two classes (3-4), but now I am confused about why did the XGBOOST and RF finish without errors, or you mean it is only an issue in the NN classification? Indeed I could see a number of classes = 2 as a hard-coded parameter.

Is there any workaround to force AMPL to work in multi-class classification mode?

**Comment by paulsonak** [comment]
Hi Marawan, 
This is something we recently discussed adding but haven't had time to do it. We'd welcome a contribution from you if you are interested!
I think we'd need at minimum: add n_classes as a parameter (parameter_parser.py) add parameter to DeepChem classifier call (model_pipeline.py?, model_wrapper.py) and update metrics to work with multiclass classification and/or not be calculated if they are binary-only (perf_data.py). There might be more changes required but those are the ones I can think of right now. Thanks!
Amanda

**Comment by paulsonak** [comment]
@stewarthe6 and I dug a little deeper - I think you should be able to use [`class_number`](https://github.com/ATOMScience-org/AMPL/blob/master/atomsci/ddm/docs/PARAMETERS.md#classifiers) in your config.json file and get the NN models to run, but the metrics will still be inaccurate. Then, an error might be thrown when the functions attempt to compute the binary classification metrics on >2 classes. This part would require updating no matter what.

**Comment by mmagithub** [comment]
Thanks paulsonac, I will give it a try. If the issue is only in the metrics, which I believe is standard anyway, does pulling another metrics.py script for example the one shipped with deepchem can solve this, or metrics calculations are attached to some other parts of the codes that will mess things up ?

**Comment by paulsonak** [comment]
I'd start with double checking the error after defining class_number in your config file. Then, tracing the code through [perf_data.py](https://github.com/ATOMScience-org/AMPL/blob/master/atomsci/ddm/pipeline/perf_data.py). Most of our metrics are pulled directly from sklearn and computed during training and at the end of training. It's definitely possible to get the predictions & compute your own metrics after training the model, but if you're not able to complete training then there would have to be some troubleshooting. 

Feel free to post a minimally reproducible example and I will take a closer look too. Thanks!

**Comment by paulsonak** [comment]
Hi @mmagithub I was able to reproduce your error. I added the line `"class_number":4` to your NN config dict and was able to successfully train a model: 
```
train_config_NN = {
"verbose": "True",
"system": "LC",
"lc_account": 'None',
"datastore": "False",
"save_results": "False",
"data_owner": "username",
"prediction_type": "classification",
"dataset_key": "./data_ready_to_model.csv",
"id_col": compound_id,
"smiles_col": smiles_col,
"response_cols": response_col,
"previously_split": "False",
"split_only": "False",
"featurizer": "ecfp",
"model_type": "NN",
"verbose": "True",
"transformers": "True",
'max_epochs': '70',
"result_dir": "./content/NN",
"splitter": "scaffold",
"split_valid_frac": "0.15",
"split_test_frac": "0.15",
"class_number":4
}
```

**Comment by mmagithub** [comment]
Interesting, thanks paulsonac. Now do the resulting performance measures will do make sense, auc-roc, Fscores, MCC scores, etc or the way it is implemented right now will make it correct only for binary classification problems?

**Comment by paulsonak** [comment]
It looks like they should all be calculated correctly, with the exception of negative predictive value which is only defined for binary models. See [here](https://github.com/ATOMScience-org/AMPL/blob/4e72449f4b37789a761d9f8fd40fa2a3a3a0221d/atomsci/ddm/pipeline/perf_data.py#L732) for the code that calculates the scores. I checked with some models based on your code and it looks reasonable, npv is indeed not calculated. 

![image](https://user-images.githubusercontent.com/64031328/197319850-8fb9c90e-190d-4651-bc55-1a47989d67b3.png)

Let us know if you have more questions!

**Comment by mmagithub** [comment]
did you manage to run the NN code till the end, I got a checkpoint read error with this config. I posted a new thread.
