### ISSUE TITLE
checkpoint reading error

### ISSUE THREAD

**Issue by mmagithub** [ATOMScience-org/AMPL#177]
Hi,

I tried to run a simple classification (multi-class) by NN, but I got this error:

['./content/NN/data_ready_to_model/NN_ecfp_scaffold_classification/d99d3881-b8d7-444c-b11d-15a067a4c7dc/model/ckpt-1', './content/NN/data_ready_to_model/NN_ecfp_scaffold_classification/d99d3881-b8d7-444c-b11d-15a067a4c7dc/model/ckpt-2', './content/NN/data_ready_to_model/NN_ecfp_scaffold_classification/d99d3881-b8d7-444c-b11d-15a067a4c7dc/model/ckpt-3', './content/NN/data_ready_to_model/NN_ecfp_scaffold_classification/d99d3881-b8d7-444c-b11d-15a067a4c7dc/model/ckpt-4', './content/NN/data_ready_to_model/NN_ecfp_scaffold_classification/d99d3881-b8d7-444c-b11d-15a067a4c7dc/model/ckpt-5']
Traceback (most recent call last):
  File "qsar_models_5HT.py", line 122, in <module>
    train_model_NN.train_model()
  File "/psi4conda/envs/atomsci/lib/python3.7/site-packages/atomsci/ddm/pipeline/model_pipeline.py", line 598, in train_model
    self.model_wrapper.train(self)
  File "/psi4conda/envs/atomsci/lib/python3.7/site-packages/atomsci/ddm/pipeline/model_wrapper.py", line 824, in train
    self.train_with_early_stopping(pipeline)
  File "/psi4conda/envs/atomsci/lib/python3.7/site-packages/atomsci/ddm/pipeline/model_wrapper.py", line 987, in train_with_early_stopping
    self._copy_model(self.best_model_dir)
  File "/psi4conda/envs/atomsci/lib/python3.7/site-packages/atomsci/ddm/pipeline/model_wrapper.py", line 1006, in _copy_model
    chkpt_file = get_latest_pytorch_checkpoint(self.model)
  File "/psi4conda/envs/atomsci/lib/python3.7/site-packages/atomsci/ddm/pipeline/model_wrapper.py", line 83, in get_latest_pytorch_checkpoint
    latest_chkpt = max(chkpts, key=os.path.getctime)
  File "/psi4conda/envs/atomsci/lib/python3.7/genericpath.py", line 65, in getctime
    return os.stat(filename).st_ctime
FileNotFoundError: [Errno 2] No such file or directory: './content/NN/data_ready_to_model/NN_ecfp_scaffold_classification/d99d3881-b8d7-444c-b11d-15a067a4c7dc/model/ckpt-1'

Here is my code:

train_config_NN = {
"verbose": "True",
"system": "LC",
"lc_account": 'None',
"datastore": "False",
"save_results": "False",
"data_owner": "username",
"prediction_type": "classification",
"dataset_key": "./data_ready_to_model.csv",
"id_col": compound_id,
"smiles_col": smiles_col,
"response_cols": response_col,
"previously_split": "False",
"split_only": "False",
"featurizer": "ecfp",
"model_type": "NN",
"verbose": "True",
"transformers": "True",
'max_epochs': '5',
"result_dir": "./content/NN",
"splitter": "scaffold",
"split_valid_frac": "0.15",
"split_test_frac": "0.15",
"class_number":num_classes
}

train_params_NN = parse.wrapper(train_config_NN)
train_model_NN = mp.ModelPipeline(train_params_NN)
train_model_NN.train_model()

**Comment by paulsonak** [comment]
I believe this usually happens when my environment has a mismatch- it’s very particular about versions of each package, especially deepchem. The current main branch requires deepchem 2.6.1- you mentioned you were testing with different versions, so I might try a full install of the whole environment. I successfully ran the code with our current dev branch, 1.5.0, but that also requires DC 2.6.1 so hopefully it will run on either. If you continue to have issues after a fresh env you can post your package versions here and we can troubleshoot more, thanks!

**Comment by mmagithub** [comment]
Thanks Paulsonac, yes I can run it now after sorting out the issue of versions. Now I would like to use the docker image, do you have any special instructions to run the docker image interactively either as a standalone or interactively through python? My attempt to use the canned image you put on docker hub was not successful, I am not sure if it is because it is outdated. Do you have written instructions on how to run it, other than using the jupyter way.

**Comment by paulsonak** [comment]
Hi, @mauvais2 might be able to help you out but in general once the docker container is up and running it is a fully contained linux-based installation, you should be able to run anything from the command line that you want. Instead of running the jupyter command you can run any other command. You do not need to first activate a virtual environment since the software is installed directly in the base env. I’d refer to the docker documentation for more information on how to use the containers.

**Comment by mmagithub** [comment]
Hi @mauvais2. I am trying to run the container using a python script but it seems the atomsci kernel is isolated. I can run the script only interactively through jupyter as outlined in the docker hub, but not sure how can I access the installed libraries directly. For example using: docker run -v $PWD:$PWD -w $PWD  atomsci/atomsci-ampl:latest /miniconda3/bin/python3 python_script.py

**Comment by paulsonak** [comment]
It sounds like you need to split that up into two separate commands. First, start the docker image- this is like a virtual machine that has all the software needed already  installed. Then, do any computation you need inside the image. The $pwd:$pwd part will connect your local drive and you can save any output there, as long as you refer to it correctly. Here are the options you can use with docker run: https://docs.docker.com/engine/reference/run/

**Comment by mmagithub** [comment]
This is not the standard procedure as far as I know and the libraries should be readily accessible. After some attempts, I realized that the atomsci is installed in an isolated conda environment, which was a bit confusing to me, and indeed I could make it run the script run I hope other users will find this helpful, and I really appreciate your prompt answers on this. This is how I ran it:   
docker run -v $PWD:$PWD -w $PWD  atomsci/atomsci-ampl:latest /miniconda3/envs/atomsci/bin/python3 script.py
