### ISSUE TITLE
Error in Ample library import

### ISSUE THREAD

**Issue by samiur130** [ATOMScience-org/AMPL#178]
**When i was trying to import Ample library according to your tutorials there is an error appeared. It's said that "torch_geometric" module is not found. Recently this error has appeared like 2 days ago. How can I solve this problem? ** 

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-4-6cefcca25baa>](https://localhost:8080/#) in <module>
     31 import atomsci.ddm.utils.data_curation_functions as dcf
     32 import atomsci.ddm.utils.curate_data as curate_data
---> 33 import atomsci.ddm.pipeline.diversity_plots as dp
     34 import atomsci.ddm.pipeline.chem_diversity as cd
     35 from atomsci.ddm.utils import struct_utils

3 frames
[/usr/local/lib/python3.7/dist-packages/deepchem/models/torch_models/dmpnn.py](https://localhost:8080/#) in <module>
      8 from deepchem.models.torch_models import TorchModel
      9 
---> 10 from torch_geometric.data import Data, Batch
     11 
     12 from deepchem.feat import GraphData

ModuleNotFoundError: No module named 'torch_geometric'

**Comment by mauvais2** [comment]
I tested with `01_Exploring_Target_Activity_ExcapeDB.ipynb`. It looks like they recently changed the default deepchem version to `2.6.2.dev`. AMPL currently supports 2.6.1. 

To get this to work for the tutorials, please replace

`! pip install --pre deepchem` in the notebook with
`! pip install 'deepchem==2.6.1'`

Thanks.

**Comment by mauvais2** [comment]
I updated all the tutorials that have the deepchem install and tested them. Please let me know if there's still an issue for you. Thanks.
