### ISSUE TITLE
Confusing wording in install instructions

### ISSUE THREAD

**Issue by stewarthe6** [ATOMScience-org/AMPL#219]
The wording in this section https://github.com/ATOMScience-org/AMPL#install-ampl is a little confusing. It makes it sound like
```
cd $GITHOME/AMPL
./build.sh
pip3 install -e .
```

is optional when it is required.

**Comment by mauvais2** [comment]
Updated the README to clarify - https://github.com/ATOMScience-org/AMPL/pull/220
