### ISSUE TITLE
Training a model on the entire data sets

### ISSUE THREAD

**Issue by mmagithub** [ATOMScience-org/AMPL#226]
Hi,

After selecting the best-performing hyperparameters, how do we train the chosen model & its hyperparameters on the full data? By default, the job settings are set to split the data and select default values for selecting top-performing models/model split, but it is not clear how we can train and save a final, production-ready model from training on the full data.
Any suggestions or tutorials for that?

Thanks,
M

**Comment by stewarthe6** [comment]
Hi, we implemented a feature to do this. It's currently sitting in a pull request. Please let us know if you run into any issues.

https://github.com/ATOMScience-org/AMPL/pull/233
