### ISSUE TITLE
Expected passes/fails for advanced testing

### ISSUE THREAD

**Issue by jonesse3** [ATOMScience-org/AMPL#227]
I ran the following commands under the section, Advanced testing, of the README. 

```
source $ENVROOT/atomsci/bin/activate # activate your pip environment. `atomsci` is an example here.
cd atomsci/ddm/test
pytest
```
It's not clear to me what is expected to pass or fail. This is what I got when running the pytest using the Docker container. 

```
The pytest (in /AMPL/atomsci/ddm/test) resulted in:======================= 51 failed, 112 passed, 266 warnings in 704.19s (0:11:44) =======================
```

Is this to be expected? It would be helpful to have more documentation in this section on expected behavior, dependencies required to set up the pytest for more passes, and why one would need to do advanced testing. 

@estahlberg
@SeanTBlack

**Comment by mauvais2** [comment]
Most of the errors are `FileNotFoundError` because most of the data files were defined using relative paths. For example: 
```
FAILED integrative/ad_index/test_ad_index.py::test - FileNotFoundError: [Errno 2] No such file or directory: 'H1_RF.json'
FAILED integrative/balancing_trans/test_balancing_transformer.py::test_balancing_transformer - FileNotFoundError: [Errno 2] ...
FAILED integrative/compare_models/test_filesystem_perf_results.py::test_RF_results - FileNotFoundError: [Errno 2] No such fi...
FAILED integrative/compare_models/test_filesystem_perf_results.py::test_NN_results - FileNotFoundError: [Errno 2] No such fi...
FAILED integrative/compare_models/test_filesystem_perf_results.py::test_XGB_results - FileNotFoundError: [Errno 2] No such f... 
```

Will update the tests and provide more info with the different tests. Currently, there's a [README ](https://github.com/ATOMScience-org/AMPL/tree/master/atomsci/ddm/test) that provides basic info on the tests that require special resources.

**Comment by mauvais2** [comment]
Per Naomi, this can be closed.
