### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by msherekar** [ATOMScience-org/AMPL#231]
Hello,
I tried creating a NN model (on colab) with graph convolution descriptors but got a type error (copied below). The script did run fine all the way to epoch 56 where it stopped after seeing no improvement. I searched for this error and looks like it is related to Loader class in YAML. If you can help on this error that will be great ! I will keep an eye on this post if there are any follow up questions.

TypeError                                 Traceback (most recent call last)

<ipython-input-20-4830a3546a53> in <cell line: 3>()
      1 train_params = parse.wrapper(train_config)
      2 train_model = mp.ModelPipeline(train_params)
----> 3 train_model.train_model()

3 frames

/usr/local/lib/python3.10/dist-packages/atomsci/ddm/pipeline/model_pipeline.py in train_model(self, featurization)
    580             return
    581 
--> 582         self.model_wrapper.train(self)
    583 
    584         # Create the metadata for the trained model

/usr/local/lib/python3.10/dist-packages/atomsci/ddm/pipeline/model_wrapper.py in train(self, pipeline)
    862             self.train_kfold_cv(pipeline)
    863         else:
--> 864             self.train_with_early_stopping(pipeline)
    865 
    866     # ****************************************************************************************

/usr/local/lib/python3.10/dist-packages/atomsci/ddm/pipeline/model_wrapper.py in train_with_early_stopping(self, pipeline)
   1025 
   1026         # Only copy the model files we need, not the entire directory
-> 1027         self._copy_model(self.best_model_dir)
   1028         self.log.info(f"Best model from epoch {self.best_epoch} saved to {self.best_model_dir}")
   1029 

/usr/local/lib/python3.10/dist-packages/atomsci/ddm/pipeline/model_wrapper.py in _copy_model(self, dest_dir)
   2590         chkpt_file = os.path.join(self.model_dir, 'checkpoint')
   2591         with open(chkpt_file, 'r') as chkpt_in:
-> 2592             chkpt_dict = yaml.load(chkpt_in.read())
   2593         chkpt_prefix = chkpt_dict['model_checkpoint_path']
   2594         files = [chkpt_file]

TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by msherekar** [comment]
Hello,
Just wanted to follow up and add versions of colab python and AMPL
Colab python version = 3.10.6
AMPL version = 1.5.1

**Comment by mauvais2** [comment]
The problem is in `yaml.load()`. AMPL uses `PyYAML` `5.4`. The latest version is `6.0.1` which the example notebook uses. From source code of `yaml.load()` from these two versions:

https://github.com/yaml/pyyaml/blob/5.4.1/lib/yaml/__init__.py#L103
```def load(stream, Loader=None):```
https://github.com/yaml/pyyaml/blob/6.0.1/lib/yaml/__init__.py#L74
```def load(stream, Loader):```

Loader used to be an optional parameter. In 6.0.1. It’s now required. Will update the `yaml.load()` calls in AMPL to work for the latest `PyYAML` in `1.6.0`, our next release. In the meantime, try install `PyYAML==5.4`.

**Comment by msherekar** [comment]
Thanks @mauvais2 ! Will try to implement version 5.4 of PyYAML.

**Comment by msherekar** [comment]
@mauvais2 : Installing PyAML==5.4 is not helping. Any other solutions?

**Comment by msherekar** [comment]
I got the following messages while installing - 

Collecting PyYAML==5.4
  Downloading PyYAML-5.4.tar.gz (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.8/174.8 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mauvais2** [comment]
I tried PyYAML 5.3.1 and got it to work.  After `! ./install_AMPL_GPU_test.sh `, I did `! pip install -U PyYAML==5.3.1`.  I was able to run `train_model.train_model()`. 

Here's my [test notebook](https://colab.research.google.com/drive/1maRBZAnaJ4tJjbJK6dRNJlbzKxjau_J4?usp=sharing) (originally from you).

**Comment by msherekar** [comment]
@mauvais2 : Thanks a lot for pointing out. I had installed PyYAML in the first line of the notebook. But now after installing after installing AMPL, I was able to run without error.
