### ISSUE TITLE
pandas error : AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by kyleoconnell-NIH** [ATOMScience-org/AMPL#234]
Getting this error with most of the atom df commands. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/tmp/ipykernel_26037/3020465164.py in ?()
     23 # smiles_col: SMILES column
     24 smiles_col = 'rdkit_smiles'
     25 
     26 # Here we are creating a new dataframe, called check_df
---> 27 check_df = curate_data.average_and_remove_duplicates(column, tolerance, 
     28                                                        list_bad_duplicates,
     29                                                        data, max_std,
     30                                                        compound_id=compound_id,

/opt/conda/envs/tensorflow/lib/python3.10/site-packages/atomsci/ddm/utils/curate_data.py in ?(column, tolerance, list_bad_duplicates, data, max_stdev, compound_id, rm_duplicate_only, smiles_col)
    621 
    622         # 5. Remove bad duplicates
    623         data = data[data.Remove_BadDuplicate != 1]
    624 
--> 625         removed = removed.append(to_remove)
    626         i = i+1
    627 
    628         # 6. If bad duplicates were removed, loop back to step 'a.' to reset table & re-calc. If no bad duplicates, exit 'while loop'.

/opt/conda/envs/tensorflow/lib/python3.10/site-packages/pandas/core/generic.py in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

### This is the main error that keep popping up
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by paulsonak** [comment]
Hi @kyleoconnell-NIH we are beta-testing an updated installation process for AMPL 1.6.0 which includes the latest versions of lots of the packages. If you'd like to test it out, you can do the following:
1. `git checkout 1.6.0` and `git pull` for latest versions
2. follow a fresh environment install but instead of `pip install --force-reinstall -r pip_requirements.txt` use `pip install --force-reinstall -r simple_requirements.txt`
Let me know if you have questions or run into issues!

**Comment by skanderhaddad** [comment]
I believe the error may be related to your Pandas version. In the requirements.txt file, you've specified 'pandas>=1.1.5.' However, in Pandas 2.0, the 'append' method has been deprecated. You have a few options to resolve this:

You can update the Pandas version to one that supports the 'append' method.
Replace 'append' with '_append' if it's suitable for your code.
Use the 'concat' function instead. Please note that the syntax for 'concat' will change, and you'll need to modify your code to use it like this: 'pd.concat([s1, s2]).'

**Comment by paulsonak** [comment]
Yep, that’s correct. Pandas has deprecated the append method in 2.x. We have updated our code to use pd.concat in the simple_pip_reqs branch and will fully release it in AMPL 1.6. I’m going to mark this as resolved. Thanks!
