### ISSUE TITLE
Examples link not working properly

### ISSUE THREAD

**Issue by ohashin2** [ATOMScience-org/AMPL#270]
When you click the [examples](https://github.com/ATOMScience-org/AMPL?tab=readme-ov-file#Example-AMPL-usage) link in the README, it does not go anywhere.  When you copy and paste the URL address, it goes to the top of the AMPL page.   If I remember correctly, there were the examples of AMPL application folders before.  Thanks.

**Comment by mauvais2** [comment]
Fixed in https://github.com/ATOMScience-org/AMPL/pull/271
