### ISSUE TITLE
Confusion matrix metrics for multi- vs single-task models

### ISSUE THREAD

**Issue by paulsonak** [ATOMScience-org/AMPL#275]
The confusion matrix that gets stored in the model metadata is internally inconsistent - for multitask models it is like:
`'confusion_matrix': [[50, 3], [0, 4]]`

and for a single task model it is embedded inside another set of brackets:
`'confusion_matrix': [[[220, 25], [11, 17]]]`

I'm not sure why the inconsistency is there, but it messes up `perf_plots.plot_confusion_matrices()`.

For now I'm checking in a quick fix to `plot_confusion_matrices` but we also probably need to update the metadata code.

**Comment by mcloughlin2** [comment]
Weird - if anything it should be the other way around. I'll look at the metadata code and see how it's handling metrics in general for multitask models.

**Comment by paulsonak** [comment]
Updated perf_plots to check for > 1 task in https://github.com/ATOMScience-org/AMPL/commit/ed92c46647a55a2056f3697a97d42f29724f59f2. If we update the metadata code, this should be reverted.
