### ISSUE TITLE
Mixed use of Morgan and ECFP fingerprints

### ISSUE THREAD

**Issue by paulsonak** [ATOMScience-org/AMPL#310]
We use RDKit Morgan fingerprints `AllChem.GetMorganFingerprintAsBitVect` in things like compare splits plots and diversity plots, but we use DeepChem `dc.feat.CircularFingerprint` to calculate ECFP fingerprints for featurization. I know these are almost the same, but they're not 100% the same so I think we should use the same fingerprints for everything, and probably it should be the ECFP from DeepChem? Although the RDKit ones are easier to implement elsewhere.

- [ ] find all instances of fingerprint calculations
- [ ] explore how difficult it is to implement ECFP from deepchem in auxiliary functions
- [ ] consider using RDKit Morgan FP's in featurization and changing all wording from ECFP to Morgan
- [ ] implement decided changes

**Comment by mcloughlin2** [comment]
Amanda, do you have specific examples where the output from AllChem.GetMorganFingerprintAsBitVect differs from that of the DeepChem function? I'm looking at the DeepChem code for CircularFingerprint._featurize, and it uses GetMorganFingerprintAsBitVect as well, so the output should be the same unless we're passing different values for the useChirality, useBondTypes and useFeatures arguments.

**Comment by mcloughlin2** [comment]
I checked the AMPL and DeepChem code and there's no difference in the useChirality, useBondTypes and useFeatures arguments. When AMPL calls the RDKit function directly, those arguments are defaulted to False, True and False, respectively. When AMPL creates a dc.feat.CircularFingerprint object, the corresponding arguments are also defaulted and in DeepChem they default to the same values.

So again, do you have examples where the fingerprints are different?

**Comment by paulsonak** [comment]
Fantastic. Apologies, I didn't dig further into the deepchem code and didn't understand that it was the same thing under the hood. I was just worried that we were actually calculating two different things in those instances. I'm glad it's all the same. I think the 'ecfp' wording is a bit misleading because the [Morgan fingerprints calculated by rdkit aren't equivalent to ECFP fingerprints](https://rdkit.org/docs/GettingStartedInPython.html#morgan-fingerprints-circular-fingerprints:~:text=The%20default%20atom%20invariants%20use%20connectivity%20information%20similar%20to%20those%20used%20for%20the%20well%20known%20ECFP%20family%20of%20fingerprints.). This is a smaller concern as long as everything is the same under the hood. Thanks!!
