### ISSUE TITLE
Misc Linter Finding Fixes

### ISSUE THREAD

**Issue by mauvais2** [ATOMScience-org/AMPL#351]
Per https://github.com/ATOMScience-org/AMPL/pull/348, Kevin's comments:

Kevin will do 1.a 1.b, 4.a. in 1.6.3.  (Do we do 3.a  in 1.6.3 or 1.7?)

Accept 2.a. 4.b.

**Comment by mcloughlin2** [comment]
OK, I made the changes for 1.a & b, 3.a and 4.b.

**Comment by mauvais2** [comment]
Fixed in bc34dcf1d44a0f608affe83f68468b139a571d9a, 86f826e8e087e46f368eff43a3b475beb1a4e5d2, 32d8b9dbbdedd84b69fce145d3a08bf07524f2ea
